### PR TITLE
Mailsender Sample Update

### PR DESCRIPTION
**Pull request by janborup**
Set the deletedMessage in Sample

### CODE REVIEW

**Comment by aelassas** [comment]
I'm working on tasktoxml in the Designer. I'll commit when it's done.

**Comment by aelassas** [comment]
I'm working on tasktoxml in the Designer. I'll commit when it's done.

**Comment by aelassas** [comment]
I'm working on tasktoxml in the Designer. I'll commit when it's done.

**Comment by janborup** [comment]
Sure - It was an error from me that this was in lastes pull request. Sorry,

**Comment by janborup** [comment]
Sure - It was an error from me that this was in lastes pull request. Sorry,

**Comment by janborup** [comment]
Sure - It was an error from me that this was in lastes pull request. Sorry,

**Comment by aelassas** [comment]
It's done. I commited. You can pull and check.

**Pull request merged**
