### PR TITLE
Sceleton for making ServerLogs to the HistoryEntry

### PR DESCRIPTION
**Pull request by janborup**
Have make all logger elements to ServerLogs list<strings>.
The return to the client site i still missing. 
[WebService HistoryEntries](http://localhost:8000/wexflow/searchHistoryEntriesByPageOrderBy?s=&from=1574554043710&to=1574911865210&page=1&entriesCount=10&heo=1)
`0: {Id: "10", WorkflowId: 69, Name: "Workflow_Startup", LaunchType: 0, Description: "Workflow_Startup",…}
Description: "Workflow_Startup"
Id: "10"
LaunchType: 0
Name: "Workflow_Startup"
ServerLogs: null
Status: 2
StatusDate: "28-11-2019 03:31:05"
WorkflowId: 69`
Maybe you can spot the Error why the HistoryEntry.Serverlogs is null, at  ?

### CODE REVIEW

**Comment by janborup** [comment]
I know what you mean with parallel execution, but do not know how to resolve that.

**Comment by aelassas** [comment]
I think if we use task.ServerLogs after running each task instead and adding that to a list then affect that list to _historyEntry.ServerLogs = list, we may have a chance to resolve the problem.

**Comment by janborup** [comment]
Don't think I have the skills to finish this the right way, so if you think you can implement it just do so.
Thanks 😅

**Comment by aelassas** [comment]
I will work on this in a different way. Thanks for your contribution.

**Comment by aelassas** [comment]
@janborup I finished this feature today. I added server logs to the dashboard and history pages. When you click on an entry, you get a popup with logs regarding the entry:

server-logs

**Comment by janborup** [comment]
Fantastic.. Great..Akram
This makes it so much easier to create/edit/test/debug tasks than before...
Great feature... Long missing.

**Pull request closed without merging**
