### PR TITLE
Merge pull request #2 from aelassas/master

### PR DESCRIPTION
**Pull request by janborup**
Update to latest

### CODE REVIEW

**Comment by janborup** [comment]
I have a problem with running the WindowsService in DEBUG mode, but don't have a clue whats wrong.
https://www.screencast.com/t/c3luPWusB

**Comment by aelassas** [comment]
Try to update to the latest version, clean your project then press F5.

Can you post the stack trace?

**Comment by janborup** [comment]
No... Updated to your last, Rebuild all, Run WindowsService with "DEBUG".... and get's this error/stack trace..

   ved Wexflow.Clients.WindowsService.WexflowWindowsService..ctor()
   ved Wexflow.Clients.WindowsService.Program.Main(String[] args) i C:\Work\WexFlow\Wexflow\src\Wexflow.Clients.WindowsService\Program.cs:linje 12
   ved System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   ved System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   ved Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   ved System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   ved System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   ved System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   ved System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   ved System.Threading.ThreadHelper.ThreadStart()

**Comment by aelassas** [comment]
I changed the way we debug wexflow windows service (see the [commit](https://github.com/aelassas/Wexflow/commit/85ab748e9ea0bedcfa22fadcedd25d9118310391)). We don't need the debug keyword anymore. just press F5 and we enter in debug mode.
Update to this version and let me know.

**Comment by janborup** [comment]
Hi.
I have pulled you new version, but the debugger says the same.

image

**Comment by aelassas** [comment]
Did you update C:\Wexflow\Wexflow.xml

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<Wexflow>
	<Setting name="workflowsFolder" value="C:\Wexflow\Workflows" />
	<Setting name="trashFolder" value="C:\Wexflow\Trash" />
	<Setting name="tempFolder" value="C:\Wexflow\Temp" />
	<Setting name="xsd" value="C:\Wexflow\Workflow.xsd" />
	<Setting name="tasksNamesFile" value="C:\Wexflow\TasksNames.json" />
	<Setting name="tasksSettingsFile" value="C:\Wexflow\TasksSettings.json" />
</Wexflow>
```

And check that the file is unlocked. (right click properties)

And put the files TasksNames.json and TasksSettings.json in C:\Wexflow\. (you can find them in [samples/Wexflow](https://github.com/aelassas/Wexflow/tree/master/samples/Wexflow)).

**Comment by janborup** [comment]
**Yes - my friend - You hit it spot on. :-)**

These lines was in my development environment but missing in the XML file the debugger used..
  <Setting name="tasksNamesFile" value="C:\Wexflow\TasksNames.json" />
  <Setting name="tasksSettingsFile" value="C:\Wexflow\TasksSettings.json" />

THANKS :-)

**Pull request closed without merging**
